[[libtasn1]]
arch = "aarch64"
git-tree-sha1 = "66050df354c55bb2747ffea12666c70585198ab7"
os = "macos"

    [[libtasn1.download]]
    sha256 = "7d3a97c8f173381d2e956ceaf29694c3c8b52dcfed3d7e005e0454b068edaee3"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.aarch64-apple-darwin.tar.gz"
[[libtasn1]]
arch = "aarch64"
git-tree-sha1 = "5001fa0cf6f4fd8c12f9ff093b3e134af6094986"
libc = "glibc"
os = "linux"

    [[libtasn1.download]]
    sha256 = "ce66c4c93820c4ee9494153f71a3f4101d2ab2577fbbf005e236fea93da0dcac"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.aarch64-linux-gnu.tar.gz"
[[libtasn1]]
arch = "aarch64"
git-tree-sha1 = "2530a0c953b5bbf1094bdc42e57b1e3466857ff9"
libc = "musl"
os = "linux"

    [[libtasn1.download]]
    sha256 = "f2347201bf93dd3b4b8f1a645bcb2f54d3859a944c20f4af8c595b444a01b4d0"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.aarch64-linux-musl.tar.gz"
[[libtasn1]]
arch = "aarch64"
git-tree-sha1 = "40777754998e97f6fd29fea75a86cd3624f244cb"
os = "freebsd"

    [[libtasn1.download]]
    sha256 = "c8ec25aaa3e05591bffa8d03097e8f9e7a77d80c9930362dc5a1ea7de2d2b9f1"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.aarch64-unknown-freebsd.tar.gz"
[[libtasn1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "637650d079d05fe7b33cb600b06212699760dfa9"
libc = "glibc"
os = "linux"

    [[libtasn1.download]]
    sha256 = "3a8545649a7651770393aa437d95ec3d7af1ba4fb6a003142029d2138bd96d49"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.armv6l-linux-gnueabihf.tar.gz"
[[libtasn1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d3d104a58c16b45276533c262ef8aeb4c8de6b73"
libc = "musl"
os = "linux"

    [[libtasn1.download]]
    sha256 = "b2c88a92b0e477ac01f19f4dba5992edcf625f63512f2a2844194178ca8185bc"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.armv6l-linux-musleabihf.tar.gz"
[[libtasn1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "abaa9b85070972d3cf52cd89e8352c1140828221"
libc = "glibc"
os = "linux"

    [[libtasn1.download]]
    sha256 = "67f1ba9e95f59c4e95f2ddf2c71125f92d8d77bd6d3d288fdb731d67fa891293"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.armv7l-linux-gnueabihf.tar.gz"
[[libtasn1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1fe3bfdbd8b260a276eb01faf8d4ce62aebc0588"
libc = "musl"
os = "linux"

    [[libtasn1.download]]
    sha256 = "4568cfa8c8213492fcafcfa9e6d1e404fdf9eea90a5fb8d1377d2790fdbc5ff8"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.armv7l-linux-musleabihf.tar.gz"
[[libtasn1]]
arch = "i686"
git-tree-sha1 = "136c0677903e89b53f4dbbbd1f5f3457ae65714c"
libc = "glibc"
os = "linux"

    [[libtasn1.download]]
    sha256 = "706247f348d0c025e7fffc69f33bd1085c4017a00cc75784d89ca675ccfa7e7e"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.i686-linux-gnu.tar.gz"
[[libtasn1]]
arch = "i686"
git-tree-sha1 = "fd81cf07a1e6f0416778ccb39c23b2f0ff5c3cfb"
libc = "musl"
os = "linux"

    [[libtasn1.download]]
    sha256 = "e83d227f7af883dc91567f47e666d0be9b59261eb885763ceb5bf6b463501994"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.i686-linux-musl.tar.gz"
[[libtasn1]]
arch = "i686"
git-tree-sha1 = "ca2ff1b8f90f6192bfe1ab1f407d16d78286cf59"
os = "windows"

    [[libtasn1.download]]
    sha256 = "f05902717d0a5c6f1816d2c0bfb02c980bafc39322798876c6b9e825c7a64444"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.i686-w64-mingw32.tar.gz"
[[libtasn1]]
arch = "powerpc64le"
git-tree-sha1 = "accba8aed09900380624e185f01a96d4a89cad9c"
libc = "glibc"
os = "linux"

    [[libtasn1.download]]
    sha256 = "1ed6378faee401ae5dc13472621928f5ee447232d0e34ae9f7a447993aeef45a"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.powerpc64le-linux-gnu.tar.gz"
[[libtasn1]]
arch = "riscv64"
git-tree-sha1 = "99aecd79aac900a7cf1a8ac5134ee3205bc0aec6"
libc = "glibc"
os = "linux"

    [[libtasn1.download]]
    sha256 = "9f0bf6b7c57ad86cd80c505501a1dbaf91bc6e5e3066d0a76c4cad93f639b891"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.riscv64-linux-gnu.tar.gz"
[[libtasn1]]
arch = "x86_64"
git-tree-sha1 = "8e78181de5565b3bbc7125c1a71f65466a6e6b11"
os = "macos"

    [[libtasn1.download]]
    sha256 = "304aa4490584f71b2c282546cd2741ebfebd78df80f9cf0d1bb2d68a0455808b"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.x86_64-apple-darwin.tar.gz"
[[libtasn1]]
arch = "x86_64"
git-tree-sha1 = "beafccb61bc89f9e00d978787d34b3078bd2ed48"
libc = "glibc"
os = "linux"

    [[libtasn1.download]]
    sha256 = "2c3346c42164f23b5a40841517708c4d1ed776fed661df7ce9b7d31aa2e7b487"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.x86_64-linux-gnu.tar.gz"
[[libtasn1]]
arch = "x86_64"
git-tree-sha1 = "7be5dcf2a265a83cf878a82ac2c35c723d2a0413"
libc = "musl"
os = "linux"

    [[libtasn1.download]]
    sha256 = "75891441f8116004403d1da84897f773f9163f57e04f0b5b20d9f0a42097fcca"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.x86_64-linux-musl.tar.gz"
[[libtasn1]]
arch = "x86_64"
git-tree-sha1 = "6fc7ae394aee9d83646f0180f578911464444e11"
os = "freebsd"

    [[libtasn1.download]]
    sha256 = "8c539f15eeaf9e2f5cf8e14ef52237e7c3784a9010e2df77e74c3a08ac9b4843"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.x86_64-unknown-freebsd.tar.gz"
[[libtasn1]]
arch = "x86_64"
git-tree-sha1 = "6328497b3baa28ce6757e3fd767313bed8ef48d4"
os = "windows"

    [[libtasn1.download]]
    sha256 = "4234e974957a3dd39d737e65f46dd6399462ea5bb830b3e0c90c60e0a8325deb"
    url = "https://github.com/JuliaBinaryWrappers/libtasn1_jll.jl/releases/download/libtasn1-v4.21.0+0/libtasn1.v4.21.0.x86_64-w64-mingw32.tar.gz"
